### ISSUE TITLE
nodejs.Error: unsupported effect at DefaultEffector.mergeEffects

### ISSUE THREAD

**Issue by lucky8jx** [node-casbin/egg-authz#2]
> 2018-12-26 20:17:45,370 ERROR 6724 [-/127.0.0.1/-/11ms GET /dataset1/resource1] nodejs.Error: unsupported effect
    at DefaultEffector.mergeEffects (D:\workspace\egg\casbin-example\node_modules\casbin\lib\effect\defaultEffector.js:52:19)
    at Enforcer.enforce (D:\workspace\egg\casbin-example\node_modules\casbin\lib\coreEnforcer.js:355:30)
    at BasicAuthorizer.checkPermission (D:\workspace\egg\casbin-example\node_modules\koa-authz\BasicAuthorizer.js:37:21)
    at D:\workspace\egg\casbin-example\node_modules\koa-authz\authz.js:31:24

My node version v10.1.0 and use command `npm run test-local` arises the issue

How to fix it? Thank you for reading!

**Comment by nodece** [comment]
Can you provide a mininze example？

**Comment by lucky8jx** [comment]
[example](https://github.com/lucky8jx/casbin-example)

**Comment by nodece** [comment]
You should add a space after `where`

```ini
[policy_effect]
e = some(where (p.eft == allow))
```

**Comment by lucky8jx** [comment]
@nodece Thanks
